/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ElButton: typeof import('element-plus/es')['ElButton']
    FullPlayer: typeof import('./src/components/FullPlayer.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    MiniPlayer: typeof import('./src/components/MiniPlayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
